//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcChat
    {
        public int gameId { get; set; }
        public System.DateTime time { get; set; }
        public bool isAgentTalk { get; set; }
        public string sentence { get; set; }
        public int runningId { get; set; }
    }
}
