//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcQuest
    {
        public string workerId { get; set; }
        public string assignmentId { get; set; }
        public int program { get; set; }
        public int smart { get; set; }
        public int offensive { get; set; }
        public int meaningless { get; set; }
        public int real { get; set; }
        public int instructionsRead { get; set; }
        public int instructNotRead { get; set; }
        public int enjoy { get; set; }
        public string comments { get; set; }
        public int interest { get; set; }
        public string hitCode { get; set; }
    }
}
