//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcWorker
    {
        public string workerId { get; set; }
        public int age { get; set; }
        public string country { get; set; }
        public string education { get; set; }
        public string gender { get; set; }
        public string culture { get; set; }
    }
}
