//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class GnBonu
    {
        public string workerId { get; set; }
        public string assignmentId { get; set; }
        public int userBonusNumber { get; set; }
        public string gameName { get; set; }
        public double bonusAmount { get; set; }
        public bool tryingToGrant { get; set; }
        public bool grantedSuccefully { get; set; }
        public System.DateTime createdTime { get; set; }
    }
}
